# code:utf-8


class ErrCode(object):
    ERR_OK = 0

    ERR_PARAMETER_NOT_FOUND = 5

    ERR_USER_NOT_LOGIN = 11
    ERR_USER_NOT_FOUND = 12
    ERR_WRONG_PASSWORD = 13
    ERR_PERMISSION_DENIED = 19

    ERR_EVENT_NOT_FOUND = 21

    ERR_LENDING_NOT_FOUND = 31

    ERR_DB_FAILED = 91
    ERR_ACTION_GET_NOT_DEFINE = 92
    ERR_ACTION_POST_NOT_DEFINE = 93
    ERR_UNKOWN_ERROR = 99
